### ISSUE TITLE
AttributeError: 'Tensor' object has no attribute 'tl_tensor_label_raw' (again)

### ISSUE THREAD

**Issue by hi-im-buggy** [johnmarktaylor91/torchlens#25]
This issue looks similar to #13, where the visualization fails with the error output:
```
AttributeError: 'Tensor' object has no attribute 'tl_tensor_label_raw'
```

I've made a [gist with a small notebook](https://gist.github.com/hi-im-buggy/021a8762e91fefd6a802e47e56d81426) to reproduce the error and see the extended logs in.

**Comment by hi-im-buggy** [comment]
I suspect this is because `InvertedResidual` in the `nn.module` includes a `ConvNormActivation` from [`torchvision.ops.misc](https://pytorch.org/vision/master/_modules/torchvision/ops/misc.html), which is probably not accounted for in torchlens (maybe it should be considered somehow in [the overridable functions](https://github.com/johnmarktaylor91/torchlens/blob/507cb5e2e6b39c162ed52991ef0719f00f3d7f84/torchlens/constants.py#L334)?)

I'm not entirely sure since I don't know how torchlens works internally.

**Comment by johnmarktaylor91** [comment]
Hello, thanks so much for raising this issue and for describing it in such detail! The notebook is super helpful. I found the issue: when the `torch.max` and `torch.min` functions are given the `dim` argument (to specify the dimension to collapse along), they don't return a tensor, but rather a tuple of tensors (one of them giving the min/max values, the other giving the indices). This is (surprisingly) the first model I've run into that includes this, so TorchLens didn't account for it. I've fixed this bug and am re-running the unit tests to make sure nothing breaks, but as soon as they finish I'll push the updated version.

**Comment by johnmarktaylor91** [comment]
Okay, pushed the fixes to GitHub and pip. Let me know if you're still getting problems.

**Comment by hi-im-buggy** [comment]
Yes, the latest version fixes the issue, thank you so much for the quick fix!

I think it would be helpful to have the commit mention the issue or vice versa, as potential contributors can see how previous issues were fixed quickly, so they can try to fix similar issues themselves once (which is what I was trying with #13 and the corresponding commit 8aec5c66e075e9649074ce626eba0f099c9a16d6).

**Comment by johnmarktaylor91** [comment]
Good suggestion, I’ll do that going forward! Closing the issue since the bug is resolved.
