### ISSUE TITLE
The output layer is equal to Linear layer, however it should not to be

### ISSUE THREAD

**Issue by whisperLiang** [johnmarktaylor91/torchlens#30]
![image](https://github.com/user-attachments/assets/ba0c751e-af28-45b6-8e01-16bf84892c0e)

Here is the code:

import torch
import torchvision
import torchlens as tl

model = torchvision.models.alexnet(pretrained=True)
x = torch.rand(1, 3, 224, 224)
model_history = tl.log_forward_pass(model, x, vis_opt='unrolled', save_function_args=True)
layer_list = model_history.layer_list
print(layer_list[-1])
print(model_history)

**Comment by johnmarktaylor91** [comment]
In TorchLens the output layer is always just a copy of the final layer. So it should indeed be the same.
