### ISSUE TITLE
colab demo throws error

### ISSUE THREAD

**Issue by grez72** [johnmarktaylor91/torchlens#4]
Was trying out the Colab demo and got the error below. Any ideas?

TypeError                                 Traceback (most recent call last)
[<ipython-input-1-b7889401bc7e>](https://localhost:8080/#) in <module>
---> 12 import torchlens as tl
     13 from cornet import cornet_s
     14 import visualpriors

4 frames
[/usr/local/lib/python3.8/dist-packages/torchlens/model_history.py](https://localhost:8080/#) in ModelHistory()
   1221 
   1222     @staticmethod
-> 1223     def _get_ancestors_from_parents(parent_entries: List[TensorLogEntry]) -> Tuple[set[str], set[str]]:
   1224         """Utility function to get the ancestors of a tensor based on those of its parent tensors.
   1225 

TypeError: 'type' object is not subscriptable

**Comment by johnmarktaylor91** [comment]
Many thanks for bringing this up and apologies for the slow turnaround—as of right now the notebook works, looks like there was temporarily a bug back in January.
